// Code generated by protoc-gen-go. DO NOT EDIT.
// source: multiboard.proto

/*
Package multiboardProto is a generated protocol buffer package.

It is generated from these files:
	multiboard.proto

It has these top-level messages:
	LoginRequest
	LoginResponse
	LogoutRequest
	LogoutResponse
	Pixel
	StreamRequest
	StreamResponse
*/
package multiboardProto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginResponse struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LogoutRequest) Reset()                    { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()               {}
func (*LogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutResponse struct {
}

func (m *LogoutResponse) Reset()                    { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()               {}
func (*LogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Pixel struct {
	X      float32 `protobuf:"fixed32,2,opt,name=x" json:"x,omitempty"`
	Y      float32 `protobuf:"fixed32,3,opt,name=y" json:"y,omitempty"`
	ColorR float32 `protobuf:"fixed32,5,opt,name=colorR" json:"colorR,omitempty"`
	ColorG float32 `protobuf:"fixed32,6,opt,name=colorG" json:"colorG,omitempty"`
	ColorB float32 `protobuf:"fixed32,7,opt,name=colorB" json:"colorB,omitempty"`
	Alpha  float32 `protobuf:"fixed32,8,opt,name=alpha" json:"alpha,omitempty"`
}

func (m *Pixel) Reset()                    { *m = Pixel{} }
func (m *Pixel) String() string            { return proto.CompactTextString(m) }
func (*Pixel) ProtoMessage()               {}
func (*Pixel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Pixel) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Pixel) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Pixel) GetColorR() float32 {
	if m != nil {
		return m.ColorR
	}
	return 0
}

func (m *Pixel) GetColorG() float32 {
	if m != nil {
		return m.ColorG
	}
	return 0
}

func (m *Pixel) GetColorB() float32 {
	if m != nil {
		return m.ColorB
	}
	return 0
}

func (m *Pixel) GetAlpha() float32 {
	if m != nil {
		return m.Alpha
	}
	return 0
}

type StreamRequest struct {
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*StreamRequest_ServerRefresh
	//	*StreamRequest_ServerDraw
	Event isStreamRequest_Event `protobuf_oneof:"event"`
}

func (m *StreamRequest) Reset()                    { *m = StreamRequest{} }
func (m *StreamRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()               {}
func (*StreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type isStreamRequest_Event interface {
	isStreamRequest_Event()
}

type StreamRequest_ServerRefresh struct {
	ServerRefresh *StreamRequest_Refresh `protobuf:"bytes,2,opt,name=server_refresh,json=serverRefresh,oneof"`
}
type StreamRequest_ServerDraw struct {
	ServerDraw *StreamRequest_Draw `protobuf:"bytes,3,opt,name=server_draw,json=serverDraw,oneof"`
}

func (*StreamRequest_ServerRefresh) isStreamRequest_Event() {}
func (*StreamRequest_ServerDraw) isStreamRequest_Event()    {}

func (m *StreamRequest) GetEvent() isStreamRequest_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *StreamRequest) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *StreamRequest) GetServerRefresh() *StreamRequest_Refresh {
	if x, ok := m.GetEvent().(*StreamRequest_ServerRefresh); ok {
		return x.ServerRefresh
	}
	return nil
}

func (m *StreamRequest) GetServerDraw() *StreamRequest_Draw {
	if x, ok := m.GetEvent().(*StreamRequest_ServerDraw); ok {
		return x.ServerDraw
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StreamRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StreamRequest_OneofMarshaler, _StreamRequest_OneofUnmarshaler, _StreamRequest_OneofSizer, []interface{}{
		(*StreamRequest_ServerRefresh)(nil),
		(*StreamRequest_ServerDraw)(nil),
	}
}

func _StreamRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StreamRequest)
	// event
	switch x := m.Event.(type) {
	case *StreamRequest_ServerRefresh:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ServerRefresh); err != nil {
			return err
		}
	case *StreamRequest_ServerDraw:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ServerDraw); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StreamRequest.Event has unexpected type %T", x)
	}
	return nil
}

func _StreamRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StreamRequest)
	switch tag {
	case 2: // event.server_refresh
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamRequest_Refresh)
		err := b.DecodeMessage(msg)
		m.Event = &StreamRequest_ServerRefresh{msg}
		return true, err
	case 3: // event.server_draw
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamRequest_Draw)
		err := b.DecodeMessage(msg)
		m.Event = &StreamRequest_ServerDraw{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StreamRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StreamRequest)
	// event
	switch x := m.Event.(type) {
	case *StreamRequest_ServerRefresh:
		s := proto.Size(x.ServerRefresh)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamRequest_ServerDraw:
		s := proto.Size(x.ServerDraw)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type StreamRequest_Draw struct {
	Pixel *Pixel `protobuf:"bytes,1,opt,name=pixel" json:"pixel,omitempty"`
}

func (m *StreamRequest_Draw) Reset()                    { *m = StreamRequest_Draw{} }
func (m *StreamRequest_Draw) String() string            { return proto.CompactTextString(m) }
func (*StreamRequest_Draw) ProtoMessage()               {}
func (*StreamRequest_Draw) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *StreamRequest_Draw) GetPixel() *Pixel {
	if m != nil {
		return m.Pixel
	}
	return nil
}

type StreamRequest_Refresh struct {
	Screen []*Pixel `protobuf:"bytes,1,rep,name=screen" json:"screen,omitempty"`
}

func (m *StreamRequest_Refresh) Reset()                    { *m = StreamRequest_Refresh{} }
func (m *StreamRequest_Refresh) String() string            { return proto.CompactTextString(m) }
func (*StreamRequest_Refresh) ProtoMessage()               {}
func (*StreamRequest_Refresh) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 1} }

func (m *StreamRequest_Refresh) GetScreen() []*Pixel {
	if m != nil {
		return m.Screen
	}
	return nil
}

type StreamResponse struct {
	Timestamp *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*StreamResponse_ClientLogin
	//	*StreamResponse_ClientLogout
	//	*StreamResponse_ClientMessage
	//	*StreamResponse_ServerShutdown
	Event isStreamResponse_Event `protobuf_oneof:"event"`
}

func (m *StreamResponse) Reset()                    { *m = StreamResponse{} }
func (m *StreamResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()               {}
func (*StreamResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type isStreamResponse_Event interface {
	isStreamResponse_Event()
}

type StreamResponse_ClientLogin struct {
	ClientLogin *StreamResponse_Login `protobuf:"bytes,2,opt,name=client_login,json=clientLogin,oneof"`
}
type StreamResponse_ClientLogout struct {
	ClientLogout *StreamResponse_Logout `protobuf:"bytes,3,opt,name=client_logout,json=clientLogout,oneof"`
}
type StreamResponse_ClientMessage struct {
	ClientMessage *StreamResponse_Message `protobuf:"bytes,4,opt,name=client_message,json=clientMessage,oneof"`
}
type StreamResponse_ServerShutdown struct {
	ServerShutdown *StreamResponse_Shutdown `protobuf:"bytes,5,opt,name=server_shutdown,json=serverShutdown,oneof"`
}

func (*StreamResponse_ClientLogin) isStreamResponse_Event()    {}
func (*StreamResponse_ClientLogout) isStreamResponse_Event()   {}
func (*StreamResponse_ClientMessage) isStreamResponse_Event()  {}
func (*StreamResponse_ServerShutdown) isStreamResponse_Event() {}

func (m *StreamResponse) GetEvent() isStreamResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *StreamResponse) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *StreamResponse) GetClientLogin() *StreamResponse_Login {
	if x, ok := m.GetEvent().(*StreamResponse_ClientLogin); ok {
		return x.ClientLogin
	}
	return nil
}

func (m *StreamResponse) GetClientLogout() *StreamResponse_Logout {
	if x, ok := m.GetEvent().(*StreamResponse_ClientLogout); ok {
		return x.ClientLogout
	}
	return nil
}

func (m *StreamResponse) GetClientMessage() *StreamResponse_Message {
	if x, ok := m.GetEvent().(*StreamResponse_ClientMessage); ok {
		return x.ClientMessage
	}
	return nil
}

func (m *StreamResponse) GetServerShutdown() *StreamResponse_Shutdown {
	if x, ok := m.GetEvent().(*StreamResponse_ServerShutdown); ok {
		return x.ServerShutdown
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*StreamResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _StreamResponse_OneofMarshaler, _StreamResponse_OneofUnmarshaler, _StreamResponse_OneofSizer, []interface{}{
		(*StreamResponse_ClientLogin)(nil),
		(*StreamResponse_ClientLogout)(nil),
		(*StreamResponse_ClientMessage)(nil),
		(*StreamResponse_ServerShutdown)(nil),
	}
}

func _StreamResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*StreamResponse)
	// event
	switch x := m.Event.(type) {
	case *StreamResponse_ClientLogin:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClientLogin); err != nil {
			return err
		}
	case *StreamResponse_ClientLogout:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClientLogout); err != nil {
			return err
		}
	case *StreamResponse_ClientMessage:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ClientMessage); err != nil {
			return err
		}
	case *StreamResponse_ServerShutdown:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ServerShutdown); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("StreamResponse.Event has unexpected type %T", x)
	}
	return nil
}

func _StreamResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*StreamResponse)
	switch tag {
	case 2: // event.client_login
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamResponse_Login)
		err := b.DecodeMessage(msg)
		m.Event = &StreamResponse_ClientLogin{msg}
		return true, err
	case 3: // event.client_logout
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamResponse_Logout)
		err := b.DecodeMessage(msg)
		m.Event = &StreamResponse_ClientLogout{msg}
		return true, err
	case 4: // event.client_message
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamResponse_Message)
		err := b.DecodeMessage(msg)
		m.Event = &StreamResponse_ClientMessage{msg}
		return true, err
	case 5: // event.server_shutdown
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(StreamResponse_Shutdown)
		err := b.DecodeMessage(msg)
		m.Event = &StreamResponse_ServerShutdown{msg}
		return true, err
	default:
		return false, nil
	}
}

func _StreamResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*StreamResponse)
	// event
	switch x := m.Event.(type) {
	case *StreamResponse_ClientLogin:
		s := proto.Size(x.ClientLogin)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamResponse_ClientLogout:
		s := proto.Size(x.ClientLogout)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamResponse_ClientMessage:
		s := proto.Size(x.ClientMessage)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *StreamResponse_ServerShutdown:
		s := proto.Size(x.ServerShutdown)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type StreamResponse_Login struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *StreamResponse_Login) Reset()                    { *m = StreamResponse_Login{} }
func (m *StreamResponse_Login) String() string            { return proto.CompactTextString(m) }
func (*StreamResponse_Login) ProtoMessage()               {}
func (*StreamResponse_Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *StreamResponse_Login) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StreamResponse_Logout struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *StreamResponse_Logout) Reset()                    { *m = StreamResponse_Logout{} }
func (m *StreamResponse_Logout) String() string            { return proto.CompactTextString(m) }
func (*StreamResponse_Logout) ProtoMessage()               {}
func (*StreamResponse_Logout) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 1} }

func (m *StreamResponse_Logout) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type StreamResponse_Message struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Pixel *Pixel `protobuf:"bytes,2,opt,name=pixel" json:"pixel,omitempty"`
}

func (m *StreamResponse_Message) Reset()                    { *m = StreamResponse_Message{} }
func (m *StreamResponse_Message) String() string            { return proto.CompactTextString(m) }
func (*StreamResponse_Message) ProtoMessage()               {}
func (*StreamResponse_Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 2} }

func (m *StreamResponse_Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StreamResponse_Message) GetPixel() *Pixel {
	if m != nil {
		return m.Pixel
	}
	return nil
}

type StreamResponse_Shutdown struct {
}

func (m *StreamResponse_Shutdown) Reset()                    { *m = StreamResponse_Shutdown{} }
func (m *StreamResponse_Shutdown) String() string            { return proto.CompactTextString(m) }
func (*StreamResponse_Shutdown) ProtoMessage()               {}
func (*StreamResponse_Shutdown) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 3} }

func init() {
	proto.RegisterType((*LoginRequest)(nil), "multiboardProto.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "multiboardProto.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "multiboardProto.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "multiboardProto.LogoutResponse")
	proto.RegisterType((*Pixel)(nil), "multiboardProto.Pixel")
	proto.RegisterType((*StreamRequest)(nil), "multiboardProto.StreamRequest")
	proto.RegisterType((*StreamRequest_Draw)(nil), "multiboardProto.StreamRequest.Draw")
	proto.RegisterType((*StreamRequest_Refresh)(nil), "multiboardProto.StreamRequest.Refresh")
	proto.RegisterType((*StreamResponse)(nil), "multiboardProto.StreamResponse")
	proto.RegisterType((*StreamResponse_Login)(nil), "multiboardProto.StreamResponse.Login")
	proto.RegisterType((*StreamResponse_Logout)(nil), "multiboardProto.StreamResponse.Logout")
	proto.RegisterType((*StreamResponse_Message)(nil), "multiboardProto.StreamResponse.Message")
	proto.RegisterType((*StreamResponse_Shutdown)(nil), "multiboardProto.StreamResponse.Shutdown")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MultiBoard service

type MultiBoardClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (MultiBoard_StreamClient, error)
}

type multiBoardClient struct {
	cc *grpc.ClientConn
}

func NewMultiBoardClient(cc *grpc.ClientConn) MultiBoardClient {
	return &multiBoardClient{cc}
}

func (c *multiBoardClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/multiboardProto.MultiBoard/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiBoardClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := grpc.Invoke(ctx, "/multiboardProto.MultiBoard/Logout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiBoardClient) Stream(ctx context.Context, opts ...grpc.CallOption) (MultiBoard_StreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MultiBoard_serviceDesc.Streams[0], c.cc, "/multiboardProto.MultiBoard/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &multiBoardStreamClient{stream}
	return x, nil
}

type MultiBoard_StreamClient interface {
	Send(*StreamRequest) error
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type multiBoardStreamClient struct {
	grpc.ClientStream
}

func (x *multiBoardStreamClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *multiBoardStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MultiBoard service

type MultiBoardServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	Stream(MultiBoard_StreamServer) error
}

func RegisterMultiBoardServer(s *grpc.Server, srv MultiBoardServer) {
	s.RegisterService(&_MultiBoard_serviceDesc, srv)
}

func _MultiBoard_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiBoardServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multiboardProto.MultiBoard/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiBoardServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiBoard_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiBoardServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/multiboardProto.MultiBoard/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiBoardServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiBoard_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MultiBoardServer).Stream(&multiBoardStreamServer{stream})
}

type MultiBoard_StreamServer interface {
	Send(*StreamResponse) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type multiBoardStreamServer struct {
	grpc.ServerStream
}

func (x *multiBoardStreamServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *multiBoardStreamServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MultiBoard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "multiboardProto.MultiBoard",
	HandlerType: (*MultiBoardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _MultiBoard_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _MultiBoard_Logout_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _MultiBoard_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "multiboard.proto",
}

func init() { proto.RegisterFile("multiboard.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0xb6, 0x43, 0xec, 0xc0, 0x38, 0x09, 0x68, 0x55, 0x21, 0xcb, 0xfd, 0xa1, 0x72, 0x05, 0xe5,
	0x50, 0x99, 0x2a, 0xed, 0xa1, 0xbd, 0xf4, 0x10, 0x55, 0xc5, 0x2a, 0x45, 0xa0, 0xa5, 0x77, 0x64,
	0xc8, 0x12, 0xa2, 0xda, 0x5e, 0x77, 0x77, 0x4d, 0xe0, 0xd8, 0xc7, 0xe9, 0x3b, 0xf5, 0x31, 0xfa,
	0x00, 0x95, 0xf7, 0xc7, 0x86, 0xe2, 0x34, 0xa8, 0xa7, 0x64, 0xbe, 0xfd, 0xe6, 0xdb, 0x99, 0x6f,
	0xc6, 0x0b, 0x1b, 0x59, 0x99, 0x8a, 0xd9, 0x19, 0x4d, 0xd8, 0x24, 0x2a, 0x18, 0x15, 0x14, 0xad,
	0x37, 0xc8, 0x71, 0x05, 0x04, 0x5b, 0x53, 0x4a, 0xa7, 0x29, 0xd9, 0x93, 0xc7, 0x67, 0xe5, 0xc5,
	0x9e, 0x98, 0x65, 0x84, 0x8b, 0x24, 0x2b, 0x54, 0x46, 0xf8, 0x01, 0xfa, 0x5f, 0xe8, 0x74, 0x96,
	0x63, 0xf2, 0xbd, 0x24, 0x5c, 0xa0, 0x00, 0x56, 0x8b, 0x84, 0xf3, 0x39, 0x65, 0x13, 0xdf, 0x7e,
	0x6e, 0xef, 0xae, 0xe1, 0x3a, 0x46, 0x08, 0xba, 0x79, 0x92, 0x11, 0xbf, 0x23, 0x71, 0xf9, 0x3f,
	0xdc, 0x86, 0x81, 0xce, 0xe7, 0x05, 0xcd, 0x39, 0x41, 0x8f, 0xc0, 0x11, 0xf4, 0x1b, 0xc9, 0x75,
	0xb6, 0x0a, 0x34, 0x8d, 0x96, 0xc2, 0xdc, 0xd3, 0x4e, 0xdb, 0x80, 0xa1, 0xa1, 0x29, 0xb9, 0xf0,
	0x87, 0x0d, 0xce, 0xf1, 0xec, 0x9a, 0xa4, 0xa8, 0x0f, 0xf6, 0xb5, 0xbc, 0xba, 0x83, 0xed, 0xeb,
	0x2a, 0xba, 0xf1, 0x57, 0x54, 0x74, 0x83, 0x36, 0xc1, 0x3d, 0xa7, 0x29, 0x65, 0xd8, 0x77, 0x24,
	0xa4, 0xa3, 0x1a, 0xdf, 0xf7, 0xdd, 0x5b, 0xf8, 0x7e, 0x8d, 0x8f, 0xfd, 0xde, 0x2d, 0x7c, 0x5c,
	0x55, 0x95, 0xa4, 0xc5, 0x65, 0xe2, 0xaf, 0x4a, 0x58, 0x05, 0xe1, 0xaf, 0x0e, 0x0c, 0x4e, 0x04,
	0x23, 0x49, 0x66, 0xaa, 0x7f, 0x07, 0x6b, 0xb5, 0x91, 0xb2, 0x03, 0x6f, 0x14, 0x44, 0xca, 0xea,
	0xc8, 0x58, 0x1d, 0x7d, 0x35, 0x0c, 0xdc, 0x90, 0xd1, 0x11, 0x0c, 0x39, 0x61, 0x57, 0x84, 0x9d,
	0x32, 0x72, 0xc1, 0x08, 0xbf, 0x94, 0x2d, 0x79, 0xa3, 0x9d, 0xe8, 0xaf, 0xd1, 0x45, 0x77, 0x6e,
	0x8c, 0xb0, 0x62, 0xc7, 0x16, 0x1e, 0xa8, 0x7c, 0x0d, 0xa0, 0x4f, 0xe0, 0x69, 0xc1, 0x09, 0x4b,
	0xe6, 0xd2, 0x12, 0x6f, 0xf4, 0x62, 0x89, 0xda, 0x47, 0x96, 0xcc, 0x63, 0x0b, 0x83, 0xca, 0xac,
	0xa2, 0xe0, 0x2d, 0x74, 0xab, 0x5f, 0xf4, 0x0a, 0x9c, 0xa2, 0xf2, 0x5b, 0xb7, 0xb5, 0x79, 0x4f,
	0x49, 0x4e, 0x03, 0x2b, 0x52, 0xf0, 0x1e, 0x7a, 0xa6, 0x90, 0x08, 0x5c, 0x7e, 0xce, 0x88, 0x1c,
	0xe9, 0xca, 0x3f, 0x32, 0x35, 0x6b, 0xdc, 0x03, 0x87, 0x5c, 0x91, 0x5c, 0x84, 0x3f, 0xbb, 0x30,
	0x34, 0xe5, 0xe9, 0x25, 0xfa, 0x7f, 0x7f, 0x3f, 0x43, 0xff, 0x3c, 0x9d, 0x91, 0x5c, 0x9c, 0xa6,
	0xd5, 0x5a, 0x6a, 0x77, 0xb7, 0x17, 0xfa, 0xa1, 0x2e, 0x8c, 0xe4, 0x0e, 0xc7, 0x16, 0xf6, 0x54,
	0xb2, 0x0c, 0xd1, 0x21, 0x0c, 0x1a, 0x2d, 0x5a, 0x0a, 0x6d, 0xee, 0xce, 0x03, 0xc4, 0x68, 0x29,
	0x62, 0x0b, 0xf7, 0x6b, 0x35, 0x5a, 0x0a, 0x74, 0x0c, 0x43, 0x2d, 0x97, 0x11, 0xce, 0x93, 0x29,
	0xf1, 0xbb, 0x52, 0xef, 0xe5, 0x32, 0xbd, 0x43, 0x45, 0xaf, 0x66, 0xaf, 0x04, 0x34, 0x80, 0x4e,
	0x60, 0x5d, 0xcf, 0x9e, 0x5f, 0x96, 0x62, 0x42, 0xe7, 0xb9, 0xdc, 0x7f, 0x6f, 0xb4, 0xbb, 0x4c,
	0xf2, 0x44, 0xf3, 0x63, 0x0b, 0xeb, 0x7d, 0x34, 0x48, 0xf0, 0x18, 0x1c, 0xd5, 0xbe, 0xf9, 0xdc,
	0xed, 0xe6, 0x73, 0x0f, 0x9e, 0x80, 0xab, 0xbb, 0x69, 0x3b, 0x3d, 0x80, 0x9e, 0x29, 0xad, 0xe5,
	0xb8, 0x59, 0xad, 0xce, 0x43, 0x56, 0x0b, 0x60, 0xd5, 0xd4, 0x54, 0xef, 0xca, 0xe8, 0xb7, 0x0d,
	0x70, 0x58, 0x65, 0x8d, 0xab, 0x2c, 0x14, 0x9b, 0x5a, 0x9f, 0xde, 0xd3, 0xba, 0xfd, 0xaa, 0x05,
	0xcf, 0x16, 0x1d, 0xeb, 0x57, 0xc6, 0x42, 0x07, 0x75, 0x63, 0xad, 0xdc, 0xe6, 0xe5, 0x0a, 0xb6,
	0x16, 0x9e, 0xd7, 0x62, 0x47, 0xe0, 0x2a, 0xbf, 0x5b, 0xc4, 0xee, 0x7c, 0x88, 0x2d, 0x62, 0x77,
	0x07, 0x15, 0x5a, 0xbb, 0xf6, 0x6b, 0xfb, 0xcc, 0x95, 0x4b, 0xff, 0xe6, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa4, 0xd8, 0x05, 0x1a, 0xf2, 0x05, 0x00, 0x00,
}
